name: PR Basic Check

on:
  pull_request:
    branches:
      - main

jobs:
  validate:
    name: ✅ Basic Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run basic check
        run: echo "Pull Request is valid"